[package]
name = "las"
version = "0.4.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Read and write point clouds stored in the ASPRS las file format."
documentation = "https://docs.rs/las"
homepage = "https://github.com/gadomski/las-rs"
repository = "https://github.com/gadomski/las-rs"
readme = "README.md"
keywords = ["lidar", "pointcloud", "las", "gis", "ASPRS"]
license = "MIT"

[dependencies]
byteorder = "0.5"
chrono = "0.2"
