[package]
name = "las"
version = "0.3.4"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Read and write point clouds stored in the ASPRS las file format."

documentation = "http://gadomski.github.io/las-rs"
homepage = "https://github.com/gadomski/las-rs"
repository = "https://github.com/gadomski/las-rs"

readme = "README.md"

keywords = ["lidar", "pointcloud", "las", "gis", "ASPRS"]

license = "MIT"

[dependencies]
byteorder = "0.5"
time = "0.1"
